<a href="https://colab.research.google.com/github/Vasista-G/GoogleCollab_Python/blob/main/Pandaslearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Owen Harris", "Henry", "Elizabeth", "Mickey"],
    "Age": [22, 35, 58, 22],
    "Gender": ["male", "male", "female", "male"]
})

df

          Name  Age  Gender
0  Owen Harris   22    male
1        Henry   35    male
2    Elizabeth   58  female
3       Mickey   22    male

In [3]:
emp = pd.read_csv("employee.csv")

emp.head()

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
0,101,Aarav Sharma,25.0,IT,Hyderabad,55000.0,2.0,2022-06-15,4.0
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
3,104,Ananya Singh,27.0,IT,Pune,68000.0,4.0,2020-01-12,3.0
4,105,Vikram Patel,35.0,Sales,Mumbai,82000.0,10.0,2014-11-05,5.0

In [ ]:
 (
emp.loc[emp["department"] == "IT", ["name", "salary","department"]]
.sort_values(by = "salary", ascending = False)
.nlargest(3, "salary")
)

            name    salary department
40  Raj Malhotra  110000.0         IT
16   Sameer Khan   91000.0         IT
36   Sameer Khan   91000.0         IT

In [ ]:
#Find employees who work in IT OR Finance

emp[(emp["department"] == "IT") | (emp["department"] == "Finance")]

In [19]:
#2.	Find employees who are from Hyderabad or Bangalore AND have a salary above 60,000

emp.loc[((emp["city"] == "Hyderabad") | (emp["city"] == "Bangalore")) & (emp["salary"] > 60000)]

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
6,107,Arjun Mehta,31.0,IT,Hyderabad,72000.0,7.0,2017-05-22,5.0
7,108,Sneha Rao,28.0,HR,Bangalore,61000.0,4.0,2020-09-14,3.0
16,117,Sameer Khan,38.0,IT,Bangalore,91000.0,13.0,2011-07-28,5.0
21,122,Priya Reddy,NaN,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
26,127,Arjun Mehta,31.0,IT,Hyderabad,72000.0,7.0,2017-05-22,5.0
27,128,Sneha Rao,28.0,HR,Bangalore,61000.0,4.0,2020-09-14,3.0
36,137,Sameer Khan,38.0,IT,Bangalore,91000.0,13.0,2011-07-28,5.0

In [23]:
'''
3.	Find employees who have:
	More than 5 years of experience
	Performance rating >= 4
	Salary > 70,000

'''

(
    emp.loc
    [
        (emp["experience_years"] > 5.0) &
        (emp["performance_rating"] >= 4) &
        (emp["salary"] > 70000),
        ["employee_id", "name", "salary"]

    ]
)

    employee_id           name    salary
2           103    Rahul Kumar   75000.0
4           105   Vikram Patel   82000.0
6           107    Arjun Mehta   72000.0
8           109    Rohan Gupta   95000.0
10          111     Karan Shah   79000.0
14          115   Manish Yadav   85000.0
16          117    Sameer Khan   91000.0
18          119  Nikhil Bansal   78000.0
24          125   Vikram Patel   82000.0
26          127    Arjun Mehta   72000.0
28          129    Rohan Gupta   95000.0
30          131     Karan Shah   79000.0
34          135   Manish Yadav   85000.0
36          137    Sameer Khan   91000.0
38          139  Nikhil Bansal   78000.0
40          141   Raj Malhotra  110000.0
42          143    Dev Agarwal   88000.0
46          147    Akash Sinha   92000.0
48          149   Varun Kapoor   81000.0

In [25]:
#4.	Find employees whose salary is between 60,000 and 80,000, inclusive.

emp[emp["salary"].between(60000, 80000)]

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
3,104,Ananya Singh,27.0,IT,Pune,68000.0,4.0,2020-01-12,3.0
6,107,Arjun Mehta,31.0,IT,Hyderabad,72000.0,7.0,2017-05-22,5.0
7,108,Sneha Rao,28.0,HR,Bangalore,61000.0,4.0,2020-09-14,3.0
10,111,Karan Shah,33.0,Sales,Pune,79000.0,9.0,2015-06-30,4.0
11,112,Meera Iyer,30.0,IT,Chennai,70000.0,6.0,2018-12-11,5.0
12,113,Aditya Joshi,27.0,Finance,Delhi,65000.0,3.0,2021-03-25,3.0
18,119,Nikhil Bansal,34.0,Finance,Pune,78000.0,9.0,2015-09-12,4.0
19,120,Tanya Roy,28.0,Sales,Kolkata,67000.0,5.0,2019-11-07,4.0
21,122,Priya Reddy,NaN,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
23,124,Ananya Singh,27.0,IT,Pune,68000.0,NaN,2020-01-12,3.0
26,127,Arjun Mehta,31.0,IT,Hyderabad,72000.0,7.0,2017-05-22,5.0
27,128,Sneha Rao,28.0,HR,Bangalore,61000.0,4.0,2020-09-14,3.0
30,131,Karan Shah,33.0,Sales,Pune,79000.0,9.0,2015-06-30,4.0
31,132,Meera Iyer,30.0,IT,Chennai,70000.0,6.0,2018-12-11,5.0
32,133,Aditya Joshi,27.0,Finance,Delhi,65000.0,3.0,2021-03-25,3.0
38,139,Nikhil Bansal,34.0,Finance,Pune,78000.0,9.0,2015-09-12,4.0
39,140,Tanya Roy,28.0,Sales,Kolkata,67000.0,5.0,2019-11-07,4.0
43,144,Kavya Pillai,31.0,Marketing,Kochi,63000.0,7.0,2017-08-25,4.0
44,145,Harsh Jain,29.0,Sales,Mumbai,71000.0,6.0,2018-04-16,3.0
45,146,Nandini Bose,27.0,IT,Kolkata,66000.0,4.0,2020-11-30,5.0
49,150,Muskan Ali,28.0,HR,Hyderabad,60000.0,5.0,2019-06-13,4.0