<a href="https://colab.research.google.com/github/Vasista-G/GoogleCollab_Python/blob/main/Pandaslearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Owen Harris", "Henry", "Elizabeth", "Mickey"],
    "Age": [22, 35, 58, 22],
    "Gender": ["male", "male", "female", "male"]
})

df

          Name  Age  Gender
0  Owen Harris   22    male
1        Henry   35    male
2    Elizabeth   58  female
3       Mickey   22    male

In [20]:
df = pd.read_csv("coffee.csv", )

df

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [21]:
df.loc[df["Day"] == "Monday", ["Day", "Units Sold"]]


#df.loc[(df["Units Sold"] > 25) & (df["Day"].isin(["Saturday", "Sunday"]))]

df[df["Day"].str.contains("sat", case = False)]

         Day Coffee Type  Units Sold
10  Saturday    Espresso          45
11  Saturday       Latte          35

In [22]:
df["Price"] = 5

def NewPrice(row):
    if row["Coffee Type"] == "Espresso":
        return 5
    else:
        return 4

df["New_price"] = df.apply(NewPrice, axis = 1)

df["Total Price"] = df["New_price"] * df["Units Sold"]

#df["New_price"] = df["Coffee Type"].apply(lambda row : 4 if row == "Espresso" else 2)

df

          Day Coffee Type  Units Sold  Price  New_price  Total Price
0      Monday    Espresso          25      5          5          125
1      Monday       Latte          15      5          4           60
2     Tuesday    Espresso          30      5          5          150
3     Tuesday       Latte          20      5          4           80
4   Wednesday    Espresso          35      5          5          175
5   Wednesday       Latte          25      5          4          100
6    Thursday    Espresso          40      5          5          200
7    Thursday       Latte          30      5          4          120
8      Friday    Espresso          45      5          5          225
9      Friday       Latte          35      5          4          140
10   Saturday    Espresso          45      5          5          225
11   Saturday       Latte          35      5          4          140
12     Sunday    Espresso          45      5          5          225
13     Sunday       Latte          35      5          4          140

In [23]:
df[df["Total Price"] > 200]

         Day Coffee Type  Units Sold  Price  New_price  Total Price
8     Friday    Espresso          45      5          5          225
10  Saturday    Espresso          45      5          5          225
12    Sunday    Espresso          45      5          5          225

In [34]:
import numpy as np

df.iloc[1:4, 1] = 'NaN'
# String NaN is not equal to np.nan so replaced it
df = df.replace('NaN', np.nan)

df.isna().sum()

Day            0
Coffee Type    3
Units Sold     0
Price          0
New_price      0
Total Price    0
dtype: int64