<a href="https://colab.research.google.com/github/Vasista-G/GoogleCollab_Python/blob/main/Pandaslearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Owen Harris", "Henry", "Elizabeth", "Mickey"],
    "Age": [22, 35, 58, 22],
    "Gender": ["male", "male", "female", "male"]
})

df

          Name  Age  Gender
0  Owen Harris   22    male
1        Henry   35    male
2    Elizabeth   58  female
3       Mickey   22    male

In [52]:
emp = pd.read_csv("employee.csv")

#emp.head()

# **Loc and iLoc and Conditional filtering**

In [ ]:
 (
emp.loc[emp["department"] == "IT", ["name", "salary","department"]]
.sort_values(by = "salary", ascending = False)
.nlargest(3, "salary")
)

            name    salary department
40  Raj Malhotra  110000.0         IT
16   Sameer Khan   91000.0         IT
36   Sameer Khan   91000.0         IT

In [ ]:
#Find employees who work in IT OR Finance

emp[(emp["department"] == "IT") | (emp["department"] == "Finance")]

In [ ]:
#2.	Find employees who are from Hyderabad or Bangalore AND have a salary above 60,000

emp.loc[((emp["city"] == "Hyderabad") | (emp["city"] == "Bangalore")) & (emp["salary"] > 60000)]

In [ ]:
'''
3.	Find employees who have:
	More than 5 years of experience
	Performance rating >= 4
	Salary > 70,000

'''

(
    emp.loc
    [
        (emp["experience_years"] > 5.0) &
        (emp["performance_rating"] >= 4) &
        (emp["salary"] > 70000),
        ["employee_id", "name", "salary"]

    ]
)

In [ ]:
#4.	Find employees whose salary is between 60,000 and 80,000, inclusive.

emp[emp["salary"].between(60000, 80000)]

In [ ]:
#5.	Find employees whose name starts with "A".

emp[emp["name"].str.startswith("A")][["employee_id", "name"]]

emp.loc[emp["name"].str.startswith("A"), ["employee_id", "name","department"]]

In [ ]:
#6.	Find employees whose name contains the letter "a", regardless of capitalization.

emp.loc[emp["name"].str.contains("a", case = False), ["employee_id", "name"]]

In [ ]:
#9.	Using .loc[], increase the salary of all IT employees by 10%.
# assign function does not modify original df. it creates a new df

emp.loc[emp["department"] == "IT", ["name","salary"]].assign(new_salary = lambda x : x["salary"] * (110/100))

In [ ]:
#10. Change the performance rating of employees with salary greater than 90,000 to 5.

#emp.loc[emp["salary"] > 90000, "performance_rating"] = 5

emp[emp["salary"] > 90000]

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
8,109,Rohan Gupta,40.0,Finance,Mumbai,95000.0,15.0,2010-02-18,5.0
16,117,Sameer Khan,38.0,IT,Bangalore,91000.0,13.0,2011-07-28,5.0
28,129,Rohan Gupta,40.0,Finance,Mumbai,95000.0,15.0,2010-02-18,5.0
36,137,Sameer Khan,38.0,IT,Bangalore,91000.0,13.0,2011-07-28,5.0
40,141,Raj Malhotra,45.0,IT,Delhi,110000.0,20.0,2005-02-14,5.0
46,147,Akash Sinha,39.0,Finance,Patna,92000.0,14.0,2011-03-08,5.0

# **Value_Counts()**

In [ ]:
#SECTION 3 - VALUE_COUNTS()

#11. Find how many employees belong to each department.

emp["department"].value_counts()

department
IT           12
Finance      10
Sales        10
Marketing    10
HR            8
Name: count, dtype: int64

In [ ]:
#14. Find the percentage of employees belonging to each department.

emp["department"].value_counts(normalize=True) * 100

department
IT           24.0
Finance      20.0
Sales        20.0
Marketing    20.0
HR           16.0
Name: proportion, dtype: float64

# **Section 4 GROUP BY**

In [ ]:
#GROUP BY

#15.Find the average salary for each department.

emp.groupby("department")["salary"].mean()

In [ ]:
#16.Find the maximum salary for each city.

emp.groupby("city", as_index= False)["salary"].max()

In [ ]:
#17.	Find the minimum and maximum salary for each department.

emp.groupby("department")["salary"].agg(max_salary = "max", min_sal = "min") # to give names to aggr columns

# Below we are specifying aggregate column in the agg function not after groupby like above
emp.groupby("department").agg(max_sal = ("salary", "max"), min_sal = ("salary","min"))

#to perform multiple aggregations on a column
emp.groupby("department")["salary"].agg(["max","min"])

#Using multiple functions for multiple columns
emp.groupby("department").agg({"salary": ["max", "min"], "experience_years": "mean"})

              salary          experience_years
                 max      min             mean
department
Finance      95000.0  65000.0         9.600000
HR           62000.0  48000.0         3.500000
IT          110000.0  55000.0         7.636364
Marketing    63000.0  52000.0         3.200000
Sales        85000.0  67000.0         8.500000

In [ ]:
#18.	Find the average salary and average experience for each department.

emp.groupby("department").agg({"salary": "mean", "experience_years": "mean"})

                  salary  experience_years
department
Finance     81222.222222          9.600000
HR          58500.000000          3.500000
IT          74000.000000          7.636364
Marketing   56500.000000          3.200000
Sales       77800.000000          8.500000

In [ ]:
#19.	Find the number of employees and average salary for each city.

#emp.groupby("city").agg(emp_Count = ("employee_id","count"), avg_sal = ("salary", "mean"))

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
0,101,Aarav Sharma,25.0,IT,Hyderabad,55000.0,2.0,2022-06-15,4.0
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
3,104,Ananya Singh,27.0,IT,Pune,68000.0,4.0,2020-01-12,3.0
4,105,Vikram Patel,35.0,Sales,Mumbai,82000.0,10.0,2014-11-05,5.0

In [ ]:
#20.	Find the average salary of employees for each performance rating.

emp.groupby("performance_rating")["salary"].mean().round(2).reset_index()

   performance_rating    salary
0                 3.0  59615.38
1                 4.0  70800.00
2                 5.0  78733.33

# **SECTION 5 - MULTIPLE AGGREGATIONS**

In [9]:
'''
For each department, calculate:

Number of employees

Average salary

Maximum salary

Minimum salary

Average experience

'''

(
    emp.groupby("department")
    .agg
     (
        count_emp = ("employee_id","count")
        , avg_sal = ("salary","mean")
        , Max_sal = ("salary", "max")
        , Min_sal = ("salary","min")
       , avg_exp = ("experience_years","mean")
     )
)

            count_emp       avg_sal   Max_sal  Min_sal   avg_exp
department
Finance            10  81222.222222   95000.0  65000.0  9.600000
HR                  8  58500.000000   62000.0  48000.0  3.500000
IT                 12  74000.000000  110000.0  55000.0  7.636364
Marketing          10  56500.000000   63000.0  52000.0  3.200000
Sales              10  77800.000000   85000.0  67000.0  8.500000

# **SECTION 6 - TRANSFORM()**

In [19]:
#Create a new column called: department_avg_salary

emp["dept_avg_sal"] = emp.groupby("department")["salary"].transform("mean")

#Create a new column called: salary_difference It should contain: Employee Salary - Department Average Salary

emp["sal_difference"] = (emp["salary"] - emp["dept_avg_sal"]).abs()

emp[["employee_id", "name", "salary", "sal_difference"]]

In [ ]:
'''
Create a new column called: above_department_average

The column should contain True or False depending on whether the
employee's salary is above their department's average salary.
'''

emp.loc[emp["salary"] > emp["dept_avg_sal"]]

# **SECTION 7 - RANKING**

In [ ]:
#Create a salary_rank column that ranks employees from highest salary to lowest salary.

emp["salary_rank"] = emp["salary"].rank(ascending= False, method = "min")

emp[["salary_rank", "salary"]].sort_values(by = "salary", ascending = False)

In [ ]:
#Find the top 5 employees based on salary.

emp[emp["salary_rank"] <= 5][["employee_id", "salary", "salary_rank"]].sort_values(by = "salary_rank")

In [ ]:
#Find the top 2 highest-paid employees from each department.

emp.sort_values(by = ["department","salary"], ascending= False).groupby("department").head(2)

# **SECTION 8 - DATE OPERATIONS**

In [53]:
#First convert joining_date into a datetime column.
#Find employees who joined after 2020-01-01.

emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         50 non-null     int64
 1   name                50 non-null     object
 2   age                 49 non-null     float64
 3   department          50 non-null     object
 4   city                50 non-null     object
 5   salary              49 non-null     float64
 6   experience_years    49 non-null     float64
 7   joining_date        49 non-null     object
 8   performance_rating  49 non-null     float64
dtypes: float64(4), int64(1), object(4)
memory usage: 3.6+ KB