<a href="https://colab.research.google.com/github/Vasista-G/GoogleCollab_Python/blob/main/PandasLvL3/PandasLvL3Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PANDAS LEVEL 3 - PRACTICE QUESTIONS**

In [ ]:
import pandas as pd

emp = pd.read_csv("employee.csv")
dept = pd.read_csv("department.csv")
bonus = pd.read_csv("bonus.csv")
sales = pd.read_csv("sales.csv")

emp.head()

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
0,101,Aarav Sharma,25.0,IT,Hyderabad,55000.0,2.0,2022-06-15,4.0
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
3,104,Ananya Singh,27.0,IT,Pune,68000.0,4.0,2020-01-12,3.0
4,105,Vikram Patel,35.0,Sales,Mumbai,82000.0,10.0,2014-11-05,5.0

In [ ]:
dept.head()

  department       manager   location   budget
0         IT  Raj Malhotra  Hyderabad  5000000
1         HR   Priya Reddy  Hyderabad  2500000
2    Finance   Rahul Kumar  Bangalore  4000000
3      Sales  Vikram Patel     Mumbai  4500000
4  Marketing    Neha Verma      Delhi  3000000

In [ ]:
#2.	Merge employees and departments using the department column.

m = pd.merge(emp, dept, on = "department", how = "inner")

m[["name", "department","manager", "location"]]

In [ ]:
#5.	Find employees who work in the same city as their department location.

m.loc[m["city"] == m["location"], ["name", "city", "location"]]

            name       city   location
0   Aarav Sharma  Hyderabad  Hyderabad
1    Priya Reddy  Hyderabad  Hyderabad
2    Rahul Kumar  Bangalore  Bangalore
4   Vikram Patel     Mumbai     Mumbai
5     Neha Verma      Delhi      Delhi
6    Arjun Mehta  Hyderabad  Hyderabad
17   Riya Kapoor      Delhi      Delhi
20  Aarav Sharma  Hyderabad  Hyderabad
21   Priya Reddy  Hyderabad  Hyderabad
22   Rahul Kumar  Bangalore  Bangalore
24  Vikram Patel     Mumbai     Mumbai
25    Neha Verma      Delhi      Delhi
26   Arjun Mehta  Hyderabad  Hyderabad
37   Riya Kapoor      Delhi      Delhi
44    Harsh Jain     Mumbai     Mumbai
49    Muskan Ali  Hyderabad  Hyderabad

In [ ]:
#7.	After merging, find the average salary for each manager.

m.groupby("manager")["salary"].mean()

manager
Neha Verma      56500.000000
Priya Reddy     58500.000000
Rahul Kumar     81222.222222
Raj Malhotra    74000.000000
Vikram Patel    77800.000000
Name: salary, dtype: float64

In [ ]:
#8.	Find the total number of employees managed by each manager.

m.groupby("manager")["employee_id"].count()

manager
Neha Verma      10
Priya Reddy      8
Rahul Kumar     10
Raj Malhotra    12
Vikram Patel    10
Name: employee_id, dtype: int64

In [ ]:
#9.	Find the highest-paid employee under each manager.

result = (
    m.loc[
        m.groupby("manager")["salary"].idxmax(),
        ["salary", "name", "manager"]
    ]
)

result

      salary          name       manager
43   63000.0  Kavya Pillai    Neha Verma
1    62000.0   Priya Reddy   Priya Reddy
8    95000.0   Rohan Gupta   Rahul Kumar
40  110000.0  Raj Malhotra  Raj Malhotra
14   85000.0  Manish Yadav  Vikram Patel

In [ ]:
#10.	Find the average salary of employees in each department along with the department budget.

m.groupby("department")[["salary", "budget"]].mean()

                  salary     budget
department
Finance     81222.222222  4000000.0
HR          58500.000000  2500000.0
IT          74000.000000  5000000.0
Marketing   56500.000000  3000000.0
Sales       77800.000000  4500000.0

# **SECTION 2 - LEFT, RIGHT AND INNER MERGE**

In [ ]:
ebm = pd.merge(emp, bonus, on = "employee_id", how = "inner")

In [ ]:
#Find employees who do not have a bonus record.

ebm.loc[~ ebm["employee_id"].isin(bonus["employee_id"]), ["employee_id", "bonus"]]

Empty DataFrame
Columns: [employee_id, bonus]
Index: []

In [ ]:
#Find employees who have received a bonus.

#emp[ebm["bonus"].notna()]

In [ ]:
#Compare the number of rows produced by:  INNER JOIN , LEFT JOIN

print(len(ebm))

ebm = pd.merge(emp, bonus, on = "employee_id", how = "inner")

print(len(ebm))

19
19

In [ ]:
#Find employees whose bonus is greater than 8,000.

ebm.loc[(ebm["bonus"] > 8000) & (ebm["salary"] > 70000), ["employee_id", "bonus"]]

# **SECTION 3 - MERGE + CALCULATED COLUMNS**

In [ ]:
'''
Merge employees with bonuses.
Create a new column: total_compensation
Formula:
salary + bonus

Create: bonus_percentage Formula: bonus / salary * 100

'''

ebm["total_compensation"] = ebm["salary"] + ebm["bonus"]

ebm["bonus_percentage"] = ebm["bonus"] / ebm["salary"] * 100

ebm[["total_compensation", "bonus_percentage"]]

In [ ]:
# 21 Find the employee with the highest total compensation.

ebm.sort_values(by = "total_compensation", ascending = False, ignore_index= True)[["total_compensation", "employee_id"]].nlargest(1, "total_compensation")

   total_compensation  employee_id
0            125000.0          141

In [ ]:
#25 Find the department with the highest total bonus.

ebm.groupby("department", as_index = False)["bonus"].sum().nlargest(1, "bonus")

  department  bonus
2         IT  61000

# **SECTION 4 - SALES DATA**

In [ ]:
#Create a new column: sales_amount Formula: quantity * unit_price
#32 Find the top 5 sales transactions.

sales["sales_amount"] = sales["quantity"] * sales["unit_price"]

sales.sort_values(by = "sales_amount", ascending = False)[["product", "category","sales_amount"]].nlargest(5, "sales_amount")

   product     category  sales_amount
16  Laptop  Electronics        210000
15   Phone  Electronics        144000
1    Phone  Electronics        125000
11  Laptop  Electronics        124000
7   Laptop  Electronics        116000

In [ ]:
#33 Find total sales by product.

sales.groupby("product")["sales_amount"].idxmax()

product
Keyboard    18
Laptop      16
Monitor     17
Mouse       19
Phone       15
Name: sales_amount, dtype: int64

In [ ]:
sales.loc[sales.groupby("product")["sales_amount"].idxmax(), ["product", "category", "sales_amount"]]

     product     category  sales_amount
18  Keyboard  Accessories         27600
16    Laptop  Electronics        210000
17   Monitor  Electronics        105000
19     Mouse  Accessories         27500
15     Phone  Electronics        144000

# **SECTION 5 - SALES + EMPLOYEE MERGE**

In [ ]:
sem = pd.merge(emp, sales, on = "employee_id", how = "inner")

#43 Find the employee who generated the highest total sales.

sem.groupby("employee_id")["sales_amount"].sum().nlargest(1)

employee_id
105    249000
Name: sales_amount, dtype: int64

# **SECTION 6 - SALES + EMPLOYEE + DEPARTMENT**

In [ ]:
sedm = (
    sales.merge(emp, on = "employee_id", how = "inner")
    .merge(dept, on = "department", how = "inner")
 )

sedm.head()

,sale_id,employee_id,product,category,quantity,unit_price,sale_date,sales_amount,name,age,department,city,salary,experience_years,joining_date,performance_rating,manager,location,budget
0,1,101,Laptop,Electronics,2,55000,2024-01-10,110000,Aarav Sharma,25.0,IT,Hyderabad,55000.0,2.0,2022-06-15,4.0,Raj Malhotra,Hyderabad,5000000
1,2,105,Phone,Electronics,5,25000,2024-01-12,125000,Vikram Patel,35.0,Sales,Mumbai,82000.0,10.0,2014-11-05,5.0,Vikram Patel,Mumbai,4500000
2,3,107,Monitor,Electronics,3,18000,2024-01-15,54000,Arjun Mehta,31.0,IT,Hyderabad,72000.0,7.0,2017-05-22,5.0,Raj Malhotra,Hyderabad,5000000
3,4,111,Keyboard,Accessories,10,2500,2024-01-18,25000,Karan Shah,33.0,Sales,Pune,79000.0,9.0,2015-06-30,4.0,Vikram Patel,Mumbai,4500000
4,5,115,Laptop,Electronics,1,60000,2024-01-22,60000,Manish Yadav,36.0,Sales,Delhi,85000.0,11.0,2013-04-21,5.0,Vikram Patel,Mumbai,4500000

In [ ]:
'''
Create a final DataFrame containing:

employee name
department
manager
department location
product
quantity
sales_amount

'''

sedm = sedm[["name", "department", "manager", "location", "product", "quantity", "sales_amount"]]

sedm.head()

,name,department,manager,location,product,quantity,sales_amount
0,Aarav Sharma,IT,Raj Malhotra,Hyderabad,Laptop,2,110000
1,Vikram Patel,Sales,Vikram Patel,Mumbai,Phone,5,125000
2,Arjun Mehta,IT,Raj Malhotra,Hyderabad,Monitor,3,54000
3,Karan Shah,Sales,Vikram Patel,Mumbai,Keyboard,10,25000
4,Manish Yadav,Sales,Vikram Patel,Mumbai,Laptop,1,60000

In [ ]:
#53 Find the manager whose team generated the highest total sales.

sedm.groupby("manager")["sales_amount"].sum().nlargest(1)

manager
Raj Malhotra    629100
Name: sales_amount, dtype: int64

# **SECTION 7 - CONCAT()**

In [ ]:
from numpy import concat
df1 = pd.DataFrame({
    "employee_id": [201, 202, 203],
    "name": ["Amit", "Ravi", "Sonia"],
    "department": ["IT", "HR", "Finance"],
    "salary": [60000, 55000, 70000]
})

df2 = pd.DataFrame({
    "employee_id": [204, 205, 206],
    "name": ["Meena", "Arun", "Priya"],
    "department": ["Sales", "IT", "Marketing"],
    "salary": [65000, 72000, 58000]
})

concat_df = pd.concat([df1,df2],  axis = 0)

concat_df

   employee_id   name department  salary
0          201   Amit         IT   60000
1          202   Ravi         HR   55000
2          203  Sonia    Finance   70000
0          204  Meena      Sales   65000
1          205   Arun         IT   72000
2          206  Priya  Marketing   58000

# **SECTION 9 - PIVOT_TABLE()**

In [ ]:
sales.head()

,sale_id,employee_id,product,category,quantity,unit_price,sale_date,sales_amount
0,1,101,Laptop,Electronics,2,55000,2024-01-10,110000
1,2,105,Phone,Electronics,5,25000,2024-01-12,125000
2,3,107,Monitor,Electronics,3,18000,2024-01-15,54000
3,4,111,Keyboard,Accessories,10,2500,2024-01-18,25000
4,5,115,Laptop,Electronics,1,60000,2024-01-22,60000

In [ ]:
# 66 Create a pivot table showing: Department Average salary Maximum salary Minimum salary

pd.pivot_table(
    m,
    index = "department",
    values = "salary",
    aggfunc = ["mean", "min", "max"],
    fill_value = 0
)

                    mean      min       max
                  salary   salary    salary
department
Finance     81222.222222  65000.0   95000.0
HR          58500.000000  48000.0   62000.0
IT          74000.000000  55000.0  110000.0
Marketing   56500.000000  52000.0   63000.0
Sales       77800.000000  67000.0   85000.0

In [ ]:
# 67 Create a pivot table showing total sales by department.


pd.pivot_table(
    sales,
    index = ["category","product"],
    values = "sales_amount",
    fill_value = 0,
    aggfunc= "sum",
    margins= True
)

# **SECTION 10 - MELT()**

In [ ]:
'''
pd.melt(
    frame,
    id_vars=None,       which show not be changed
    value_vars=None,    Which column to be melted
    var_name=None,      Name of the new column
    value_name="value", Values Name of the new column
    col_level=None,     Which column to be melted
    ignore_index=True   Ignore index
)

'''


data = {
    "employee_id": [101, 102, 103, 104],
    "name": ["Aarav", "Priya", "Rahul", "Ananya"],
    "January": [50000, 45000, 60000, 40000],
    "February": [55000, 48000, 62000, 45000],
    "March": [60000, 52000, 65000, 47000],
    "April": [58000, 55000, 68000, 50000]
}

df = pd.DataFrame(data)

# 72 Convert this DataFrame from wide format to long format using melt().

melt_Date = pd.melt(df)

In [ ]:
melt_Date = pd.melt(
    df,
    id_vars = ["employee_id", "name"],
    value_vars = ["January", "February", "March", "April"],
    var_name= "month",
    value_name = "salary"
)

#75 Find total sales for each month.

melt_Date.groupby("month").agg(Total_sales = ("salary", "sum"))

# 76 Find the month with the highest total sales.
melt_Date[melt_Date["salary"] == melt_Date["salary"].max()][["month", "salary"]]

    month  salary
14  April   68000

In [ ]:
# 77 Convert the melted DataFrame back to wide format.

pd.pivot(
    melt_Date,
    index = "employee_id",
    columns= ["month"],
    values=["salary"]

)

# **SECTION 12 - CUT() AND QCUT()**

In [ ]:
'''
pd.cut(
    x,                      Data to divide
    bins,                   Number of bins or bin boundaries
    right=True,             Whether right edge is included
    labels=None,            Names for the bins
    retbins=False,          Return calculated bin edges
    precision=3,            Decimal precision displayed
    include_lowest=False,   Include lowest boundary
    duplicates='raise',     How to handle duplicate edges
    ordered=True            Whether categories are ordered
)

'''
data = {
    "employee_id": [101, 102, 103, 104],
    "name": ["Aarav", "Priya", "Rahul", "Ananya"],
    "January": [50000, 45000, 60000, 40000],
    "February": [55000, 48000, 62000, 45000],
    "March": [60000, 52000, 65000, 47000],
    "April": [58000, 55000, 68000, 50000]
}

pd.DataFrame(data)

pd.cut(
    data["January"],
    bins = 5
)

[(48000.0, 52000.0], (44000.0, 48000.0], (56000.0, 60000.0], (39980.0, 44000.0]]
Categories (5, interval[float64, right]): [(39980.0, 44000.0] < (44000.0, 48000.0] <
                                           (48000.0, 52000.0] < (52000.0, 56000.0] <
                                           (56000.0, 60000.0]]

# **SECTION 13 - MAP() AND REPLACE()**

In [ ]:
#89 Use map() to convert performance ratings:
# 1 -> Poor
# 2 -> Below Average
# 3 -> Average
# 4 -> Good
# 5 -> Excellent

emp.head()

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
0,101,Aarav Sharma,25.0,IT,Hyderabad,55000.0,2.0,2022-06-15,4.0
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
3,104,Ananya Singh,27.0,IT,Pune,68000.0,4.0,2020-01-12,3.0
4,105,Vikram Patel,35.0,Sales,Mumbai,82000.0,10.0,2014-11-05,5.0

In [ ]:
emp["performance_rating"].map({
    1:"Poor",
    2:"Below Average",
    3:"Average",
    4:"Good",
    5:"Excellent"
}).head()

# The difference between Map() and Replace() is Map Gives NaN if the lookup is not not found
# Replace simply gives the original value present instead of NaN

emp["performance_rating"].replace({
    1:"Poor",
    2:"Below Average",
    3:"Average",
    4:"Good"
}).head()

0       Good
1        5.0
2       Good
3    Average
4        5.0
Name: performance_rating, dtype: object

# **SECTION 14 - DUPLICATES**

In [ ]:
#93 Find duplicate employee names.

emp.head()

#using Map
emp[emp["name"].map(emp["name"].value_counts()) > 1]

#using duplicated
emp["name"].duplicated(keep= False)