<a href="https://colab.research.google.com/github/Vasista-G/GoogleCollab_Python/blob/main/PandasLvL3/PandasLvL3Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PANDAS LEVEL 3 - PRACTICE QUESTIONS**

In [38]:
import pandas as pd

emp = pd.read_csv("employee.csv")
dept = pd.read_csv("department.csv")
bonus = pd.read_csv("bonus.csv")
sales = pd.read_csv("sales.csv")

emp.head()

,employee_id,name,age,department,city,salary,experience_years,joining_date,performance_rating
0,101,Aarav Sharma,25.0,IT,Hyderabad,55000.0,2.0,2022-06-15,4.0
1,102,Priya Reddy,29.0,HR,Hyderabad,62000.0,5.0,2019-03-20,5.0
2,103,Rahul Kumar,32.0,Finance,Bangalore,75000.0,8.0,2016-08-10,4.0
3,104,Ananya Singh,27.0,IT,Pune,68000.0,4.0,2020-01-12,3.0
4,105,Vikram Patel,35.0,Sales,Mumbai,82000.0,10.0,2014-11-05,5.0

In [16]:
dept.head()

  department       manager   location   budget
0         IT  Raj Malhotra  Hyderabad  5000000
1         HR   Priya Reddy  Hyderabad  2500000
2    Finance   Rahul Kumar  Bangalore  4000000
3      Sales  Vikram Patel     Mumbai  4500000
4  Marketing    Neha Verma      Delhi  3000000

In [17]:
#2.	Merge employees and departments using the department column.

m = pd.merge(emp, dept, on = "department", how = "inner")

m[["name", "department","manager", "location"]]

             name department       manager   location
0    Aarav Sharma         IT  Raj Malhotra  Hyderabad
1     Priya Reddy         HR   Priya Reddy  Hyderabad
2     Rahul Kumar    Finance   Rahul Kumar  Bangalore
3    Ananya Singh         IT  Raj Malhotra  Hyderabad
4    Vikram Patel      Sales  Vikram Patel     Mumbai
5      Neha Verma  Marketing    Neha Verma      Delhi
6     Arjun Mehta         IT  Raj Malhotra  Hyderabad
7       Sneha Rao         HR   Priya Reddy  Hyderabad
8     Rohan Gupta    Finance   Rahul Kumar  Bangalore
9     Ishita Nair  Marketing    Neha Verma      Delhi
10     Karan Shah      Sales  Vikram Patel     Mumbai
11     Meera Iyer         IT  Raj Malhotra  Hyderabad
12   Aditya Joshi    Finance   Rahul Kumar  Bangalore
13    Pooja Desai  Marketing    Neha Verma      Delhi
14   Manish Yadav      Sales  Vikram Patel     Mumbai
15    Divya Menon         HR   Priya Reddy  Hyderabad
16    Sameer Khan         IT  Raj Malhotra  Hyderabad
17    Riya Kapoor  Marketing    Neha Verma      Delhi
18  Nikhil Bansal    Finance   Rahul Kumar  Bangalore
19      Tanya Roy      Sales  Vikram Patel     Mumbai
20   Aarav Sharma         IT  Raj Malhotra  Hyderabad
21    Priya Reddy         HR   Priya Reddy  Hyderabad
22    Rahul Kumar    Finance   Rahul Kumar  Bangalore
23   Ananya Singh         IT  Raj Malhotra  Hyderabad
24   Vikram Patel      Sales  Vikram Patel     Mumbai
25     Neha Verma  Marketing    Neha Verma      Delhi
26    Arjun Mehta         IT  Raj Malhotra  Hyderabad
27      Sneha Rao         HR   Priya Reddy  Hyderabad
28    Rohan Gupta    Finance   Rahul Kumar  Bangalore
29    Ishita Nair  Marketing    Neha Verma      Delhi
30     Karan Shah      Sales  Vikram Patel     Mumbai
31     Meera Iyer         IT  Raj Malhotra  Hyderabad
32   Aditya Joshi    Finance   Rahul Kumar  Bangalore
33    Pooja Desai  Marketing    Neha Verma      Delhi
34   Manish Yadav      Sales  Vikram Patel     Mumbai
35    Divya Menon         HR   Priya Reddy  Hyderabad
36    Sameer Khan         IT  Raj Malhotra  Hyderabad
37    Riya Kapoor  Marketing    Neha Verma      Delhi
38  Nikhil Bansal    Finance   Rahul Kumar  Bangalore
39      Tanya Roy      Sales  Vikram Patel     Mumbai
40   Raj Malhotra         IT  Raj Malhotra  Hyderabad
41    Simran Kaur         HR   Priya Reddy  Hyderabad
42    Dev Agarwal    Finance   Rahul Kumar  Bangalore
43   Kavya Pillai  Marketing    Neha Verma      Delhi
44     Harsh Jain      Sales  Vikram Patel     Mumbai
45   Nandini Bose         IT  Raj Malhotra  Hyderabad
46    Akash Sinha    Finance   Rahul Kumar  Bangalore
47     Shreya Das  Marketing    Neha Verma      Delhi
48   Varun Kapoor      Sales  Vikram Patel     Mumbai
49     Muskan Ali         HR   Priya Reddy  Hyderabad

In [18]:
#5.	Find employees who work in the same city as their department location.

m.loc[m["city"] == m["location"], ["name", "city", "location"]]

            name       city   location
0   Aarav Sharma  Hyderabad  Hyderabad
1    Priya Reddy  Hyderabad  Hyderabad
2    Rahul Kumar  Bangalore  Bangalore
4   Vikram Patel     Mumbai     Mumbai
5     Neha Verma      Delhi      Delhi
6    Arjun Mehta  Hyderabad  Hyderabad
17   Riya Kapoor      Delhi      Delhi
20  Aarav Sharma  Hyderabad  Hyderabad
21   Priya Reddy  Hyderabad  Hyderabad
22   Rahul Kumar  Bangalore  Bangalore
24  Vikram Patel     Mumbai     Mumbai
25    Neha Verma      Delhi      Delhi
26   Arjun Mehta  Hyderabad  Hyderabad
37   Riya Kapoor      Delhi      Delhi
44    Harsh Jain     Mumbai     Mumbai
49    Muskan Ali  Hyderabad  Hyderabad

In [19]:
#7.	After merging, find the average salary for each manager.

m.groupby("manager")["salary"].mean()

manager
Neha Verma      56500.000000
Priya Reddy     58500.000000
Rahul Kumar     81222.222222
Raj Malhotra    74000.000000
Vikram Patel    77800.000000
Name: salary, dtype: float64

In [20]:
#8.	Find the total number of employees managed by each manager.

m.groupby("manager")["employee_id"].count()

manager
Neha Verma      10
Priya Reddy      8
Rahul Kumar     10
Raj Malhotra    12
Vikram Patel    10
Name: employee_id, dtype: int64

In [21]:
#9.	Find the highest-paid employee under each manager.

result = (
    m.loc[
        m.groupby("manager")["salary"].idxmax(),
        ["salary", "name", "manager"]
    ]
)

result

      salary          name       manager
43   63000.0  Kavya Pillai    Neha Verma
1    62000.0   Priya Reddy   Priya Reddy
8    95000.0   Rohan Gupta   Rahul Kumar
40  110000.0  Raj Malhotra  Raj Malhotra
14   85000.0  Manish Yadav  Vikram Patel

In [22]:
#10.	Find the average salary of employees in each department along with the department budget.

m.groupby("department")[["salary", "budget"]].mean()

                  salary     budget
department
Finance     81222.222222  4000000.0
HR          58500.000000  2500000.0
IT          74000.000000  5000000.0
Marketing   56500.000000  3000000.0
Sales       77800.000000  4500000.0

# **SECTION 2 - LEFT, RIGHT AND INNER MERGE**

In [23]:
ebm = pd.merge(emp, bonus, on = "employee_id", how = "inner")

In [24]:
#Find employees who do not have a bonus record.

ebm.loc[~ ebm["employee_id"].isin(bonus["employee_id"]), ["employee_id", "bonus"]]

Empty DataFrame
Columns: [employee_id, bonus]
Index: []

In [25]:
#Find employees who have received a bonus.

#emp[ebm["bonus"].notna()]

In [26]:
#Compare the number of rows produced by:  INNER JOIN , LEFT JOIN

print(len(ebm))

ebm = pd.merge(emp, bonus, on = "employee_id", how = "inner")

print(len(ebm))

19
19

In [27]:
#Find employees whose bonus is greater than 8,000.

ebm.loc[(ebm["bonus"] > 8000) & (ebm["salary"] > 70000), ["employee_id", "bonus"]]

    employee_id  bonus
4           105  10000
5           107   9000
6           109  12000
9           115  11000
10          117  13000
11          119   8500
13          141  15000
14          143  10000
17          149   9000

# **SECTION 3 - MERGE + CALCULATED COLUMNS**

In [ ]:
'''
Merge employees with bonuses.
Create a new column: total_compensation
Formula:
salary + bonus

Create: bonus_percentage Formula: bonus / salary * 100

'''

ebm["total_compensation"] = ebm["salary"] + ebm["bonus"]

ebm["bonus_percentage"] = ebm["bonus"] / ebm["salary"] * 100

ebm[["total_compensation", "bonus_percentage"]]

In [29]:
# 21 Find the employee with the highest total compensation.

ebm.sort_values(by = "total_compensation", ascending = False, ignore_index= True)[["total_compensation", "employee_id"]].nlargest(1, "total_compensation")

   total_compensation  employee_id
0            125000.0          141

In [30]:
#25 Find the department with the highest total bonus.

ebm.groupby("department", as_index = False)["bonus"].sum().nlargest(1, "bonus")

  department  bonus
2         IT  61000

# **SECTION 4 - SALES DATA**

In [57]:
#Create a new column: sales_amount Formula: quantity * unit_price
#32 Find the top 5 sales transactions.

sales["sales_amount"] = sales["quantity"] * sales["unit_price"]

sales.sort_values(by = "sales_amount", ascending = False)[["product", "category","sales_amount"]].nlargest(5, "sales_amount")

   product     category  sales_amount
16  Laptop  Electronics        210000
15   Phone  Electronics        144000
1    Phone  Electronics        125000
11  Laptop  Electronics        124000
7   Laptop  Electronics        116000

In [32]:
#33 Find total sales by product.

sales.groupby("product")["sales_amount"].idxmax()

product
Keyboard    18
Laptop      16
Monitor     17
Mouse       19
Phone       15
Name: sales_amount, dtype: int64

In [33]:
sales.loc[sales.groupby("product")["sales_amount"].idxmax(), ["product", "category", "sales_amount"]]

     product     category  sales_amount
18  Keyboard  Accessories         27600
16    Laptop  Electronics        210000
17   Monitor  Electronics        105000
19     Mouse  Accessories         27500
15     Phone  Electronics        144000

# **SECTION 5 - SALES + EMPLOYEE MERGE**

In [34]:
sem = pd.merge(emp, sales, on = "employee_id", how = "inner")

#43 Find the employee who generated the highest total sales.

sem.groupby("employee_id")["sales_amount"].sum().nlargest(1)

employee_id
105    249000
Name: sales_amount, dtype: int64

# **SECTION 6 - SALES + EMPLOYEE + DEPARTMENT**

In [ ]:
sedm = (
    sales.merge(emp, on = "employee_id", how = "inner")
    .merge(dept, on = "department", how = "inner")
 )

sedm.head()

In [ ]:
'''
Create a final DataFrame containing:

employee name
department
manager
department location
product
quantity
sales_amount

'''

sedm = sedm[["name", "department", "manager", "location", "product", "quantity", "sales_amount"]]

sedm.head()

In [37]:
#53 Find the manager whose team generated the highest total sales.

sedm.groupby("manager")["sales_amount"].sum().nlargest(1)

manager
Raj Malhotra    629100
Name: sales_amount, dtype: int64

# **SECTION 7 - CONCAT()**

In [44]:
from numpy import concat
df1 = pd.DataFrame({
    "employee_id": [201, 202, 203],
    "name": ["Amit", "Ravi", "Sonia"],
    "department": ["IT", "HR", "Finance"],
    "salary": [60000, 55000, 70000]
})

df2 = pd.DataFrame({
    "employee_id": [204, 205, 206],
    "name": ["Meena", "Arun", "Priya"],
    "department": ["Sales", "IT", "Marketing"],
    "salary": [65000, 72000, 58000]
})

concat_df = pd.concat([df1,df2],  axis = 0)

concat_df

   employee_id   name department  salary
0          201   Amit         IT   60000
1          202   Ravi         HR   55000
2          203  Sonia    Finance   70000
0          204  Meena      Sales   65000
1          205   Arun         IT   72000
2          206  Priya  Marketing   58000

# **SECTION 9 - PIVOT_TABLE()**

In [58]:
sales.head()

,sale_id,employee_id,product,category,quantity,unit_price,sale_date,sales_amount
0,1,101,Laptop,Electronics,2,55000,2024-01-10,110000
1,2,105,Phone,Electronics,5,25000,2024-01-12,125000
2,3,107,Monitor,Electronics,3,18000,2024-01-15,54000
3,4,111,Keyboard,Accessories,10,2500,2024-01-18,25000
4,5,115,Laptop,Electronics,1,60000,2024-01-22,60000

In [60]:
# 66 Create a pivot table showing: Department Average salary Maximum salary Minimum salary

pd.pivot_table(
    m,
    index = "department",
    values = "salary",
    aggfunc = ["mean", "min", "max"],
    fill_value = 0
)

                    mean      min       max
                  salary   salary    salary
department
Finance     81222.222222  65000.0   95000.0
HR          58500.000000  48000.0   62000.0
IT          74000.000000  55000.0  110000.0
Marketing   56500.000000  52000.0   63000.0
Sales       77800.000000  67000.0   85000.0

In [63]:
# 67 Create a pivot table showing total sales by department.


pd.pivot_table(
    sales,
    index = "product",
    values = "sales_amount",
    fill_value = 0,
    margins= True
)

           sales_amount
product
Keyboard   23400.000000
Laptop    114166.666667
Monitor    80000.000000
Mouse      21833.333333
Phone     114750.000000
All        79985.000000